### ISSUE TITLE
Discussion cards are inproperly coloured when browser is in light mode

### ISSUE THREAD

**Issue by testsnake** [BCharity-Net/bcit24jan#15]
On at least Gecko (Firefox) and Blink (Chrome, Edge, etc) browsers, the discussion cards and text are invisible on Light mode

![image](https://github.com/BCharity-Net/bcit24jan/assets/12944119/42a7a322-c1a9-4461-8c8e-adedad907095)

When switching to dark mode, they are just fine

![image](https://github.com/BCharity-Net/bcit24jan/assets/12944119/17cb2ef9-d009-45ff-b520-1f682d48326c)

Cards should be changed to permanently act in the dark mode state

**Comment by John2T** [comment]
Fixed, tested on firefox and google chrome
